adminnginx:
    image: agaveapi/admin_services_nginx
    links:
        - adminjwt
        - adminaccounts
    ports:
        - "8000:80"
    command: /bin/bash -c "env && envsubst < /etc/nginx/sites-enabled/flask-project.template > /etc/nginx/sites-enabled/flask-project && rm -f /etc/nginx/sites-enabled/flask-project.template && nginx -g 'daemon off;'"


adminjwt:
    image: agaveapi/flask_admin_services
    ports:
        - "5000:5000"
#    volumes:
#        - ./local-dev.conf:/etc/service.conf
    environment:
        package: /services/jwt

# need to export wso2admin_password before starting up the services
adminaccounts:
    image: agaveapi/flask_admin_services
    ports:
        - "5001:5000"
#    volumes:
#        - ./local-dev.conf:/etc/service.conf
    extra_hosts:
        dev.tenants.sandbox.agaveapi.co: 129.114.6.148
    environment:
        package: /services/accounts
        wso2admin_username: admin
        wso2admin_password:
        base_url: dev.tenants.sandbox.agaveapi.co
        port: 9443