#nginx:
#    image: agaveapi/admin_nginx
#    ports:
#        - "8000:80"

jwt:
    image: agaveapi/flask_admin_services
    ports:
        - "5000:5000"
    volumes:
        - ./local-dev.conf:/etc/service.conf
    environment:
        package: /services/jwt

accounts:
    image: agaveapi/flask_admin_services
    ports:
        - "5001:5000"
    volumes:
        - ./local-dev.conf:/etc/service.conf
    environment:
        package: /services/accounts
        wso2admin_username: admin
        wso2admin_password: a2m1np@ss

